name: whoami

volumes:
  ts-whoami-state:

services:
  whoami:
    image: traefik/whoami
    depends_on:
      - ts-whoami
    network_mode: service:ts-whoami
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
  
  ts-whoami:
    image: tailscale/tailscale:v1.68.1
    hostname: whoami
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY:?required TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - ts-whoami-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped