name: whoami

volumes:
  ts-whoami-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  whoami:
    image: traefik/whoami
    #depends_on:
    #  ts-whoami:
    #    condition: service_healthy
    network_mode: service:ts-whoami
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
    restart: unless-stopped

  ts-whoami:
    image: tailscale/tailscale:v1.78.1
    hostname: whoami
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    volumes:
      - ts-whoami-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
