name: whoami

volumes:
  ts-whoami-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  whoami:
    image: traefik/whoami
    depends_on:
      ts-whoami:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M
    network_mode: service:ts-whoami
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
    restart: unless-stopped

  ts-whoami:
    image: tailscale/tailscale:stable
    hostname: whoami
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container  --reset
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
      TS_USERSPACE: false
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - ts-whoami-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
