name: prowlarr

volumes:
  prowlarr-config:
  ts-prowlarr-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.0.5
    depends_on:
      ts-prowlarr:
        condition: service_started
    network_mode: service:ts-prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Budapest
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  ts-prowlarr:
    image: tailscale/tailscale:stable
    hostname: prowlarr
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container --reset
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
      TS_ACCEPT_DNS: "true"
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - ts-prowlarr-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped