name: Service deployer
description: Deploys a service to a remote host

inputs:
  host:
    description: The host where the service gets deployed
    required: true
  service_root_dir:
    description: The deployment root directory where the service gets deployed
    required: true
  service_dir_name:
    description: The name of the service directory
    required: true
  infisical_client_id:
    description: The Infisical client id
    required: true
  infisical_client_secret:
    description: The Infisical client secret
    required: true
  infisical_project_id:
    description: The Infisical project id
    required: true
  infisical_secret_path:
    description: The services Infisical secrets folder
    required: true

runs:
  using: "composite"

  steps:
    - run: rsync -avz --del ${{ inputs.service_dir_name }} ${{ inputs.host }}:${{ inputs.service_root_dir }}/
      shell: bash
    - run: rsync -avz service_deploy.sh ${{ inputs.host }}:${{ inputs.service_root_dir }}/${{ inputs.service_dir_name }}
      shell: bash
    - run: rsync -avz .infisical.json ${{ inputs.host }}:${{ inputs.service_root_dir }}/${{ inputs.service_dir_name }}
      shell: bash
    - name: Deploy
      env: 
        DEPLOY_DIR: ${{ inputs.service_root_dir }}/${{ inputs.service_dir_name }}
        PROJECT_ID: ${{ inputs.infisical_project_id }}
        CLIENT_ID: ${{ inputs.infisical_client_id }}
        CLIENT_SECRET: ${{ inputs.infisical_client_secret }}
        SECRET_PATH: ${{ inputs.infisical_secret_path }}
      shell: bash
      run: |
        ssh ${{ inputs.host }} "
            cd \"$DEPLOY_DIR\" || exit
            export PROJECT_ID=$PROJECT_ID
            export CLIENT_ID=$CLIENT_ID
            export CLIENT_SECRET=$CLIENT_SECRET
            export SECRET_PATH=$SECRET_PATH
            ./.github/service_deploy.sh
        "