name: scrutiny

volumes:
  influxdb:
  scrutiny-web-config:
  ts-scrutiny-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  influxdb:
    image: influxdb:2.7
    network_mode: service:ts-scrutiny
    depends_on:
      ts-scrutiny:
        condition: service_started
    volumes:
      - "influxdb:/var/lib/influxdb2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
    restart: unless-stopped

  web:
    image: "ghcr.io/analogj/scrutiny:v0.8.1-web"
    network_mode: service:ts-scrutiny
    volumes:
      - "scrutiny-web-config:/opt/scrutiny/config"
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: "localhost"
      SCRUTINY_NOTIFY_URLS: ${NOTIFY_URLS}
    depends_on:
      ts-scrutiny:
        condition: service_started
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  collector:
    image: "ghcr.io/analogj/scrutiny:v0.8.1-collector"
    network_mode: service:ts-scrutiny
    cap_add:
      - SYS_RAWIO
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/run/udev:/run/udev:ro"
    environment:
      COLLECTOR_API_ENDPOINT: "http://localhost:8080"
      COLLECTOR_HOST_ID: "Solitude"
      COLLECTOR_CRON_SCHEDULE: "0 0 * * *"
      COLLECTOR_RUN_STARTUP: true
    depends_on:
      ts-scrutiny:
        condition: service_started
      web:
        condition: service_healthy
    devices:
      - /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S2R6NX0J148963D:/dev/sda
      - /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S2R6NX0JB33102W:/dev/sdb
      - /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S3R0NF0J828721F:/dev/sdc
      - /dev/disk/by-id/ata-WDC_WD20SPZX-22UA7T0_WD-WXT2E319NKCA:/dev/sdd
      - /dev/disk/by-id/ata-ST4000VN006-3CW104_WW659070S:/dev/sde
      - /dev/disk/by-id/ata-ST4000VN006-3CW104_ZW63A03S:/dev/sdf
    restart: unless-stopped

  ts-scrutiny:
    image: tailscale/tailscale:stable
    hostname: scrutiny
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - ts-scrutiny-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
