name: jellyfin

volumes:
  jellyfin-config:
  tailscale-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    depends_on:
      tailscale:
        condition: service_started
    network_mode: service:tailscale
    environment:
      TZ: Europe/Budapest
      PUID: 1000
      PGID: 1000
      JELLYFIN_PublishedServerUrl: jellyfin.bittern-royal.ts.net
    volumes:
      - jellyfin-config:/config
      - /data/media:/data
    devices:
      - /dev/dri:/dev/dri       # GPU acceleration
      - /dev/video0:/dev/video0 # V4L2 device
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:stable
    hostname: jellyfin
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
