name: jellyfin

volumes:
  jellyfin-config:
  ts-jellyfin-state:

services:
  jellyfin:
    image: linuxserver/jellyfin:10.9.2
    depends_on:
      - ts-jellyfin
    network_mode: service:ts-jellyfin
    environment:
      TZ: Europe/Budapest
      PUID: 1000
      PGID: 1000
    volumes:
      - jellyfin-config:/config
      - /data/media:/data
    restart: unless-stopped
  
  ts-jellyfin:
    image: tailscale/tailscale:v1.66.4
    hostname: jellyfin
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY:?required TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_SERVE_CONFIG: /config/jellyfin.json
      TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - ts-jellyfin-state:/var/lib/tailscale
      - ./ts-jellyfin/config:/config:ro
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    