name: jellyfin

volumes:
  jellyfin-config:
  ts-jellyfin-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  jellyfin:
    image: linuxserver/jellyfin:10.9.10
    depends_on:
      ts-jellyfin:
        condition: service_healthy
    network_mode: service:ts-jellyfin
    environment:
      TZ: Europe/Budapest
      PUID: 1000
      PGID: 1000
    volumes:
      - jellyfin-config:/config
      - /data/media:/data
    restart: unless-stopped
  
  ts-jellyfin:
    image: tailscale/tailscale:v1.70.0
    hostname: jellyfin
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container --reset
      TS_SERVE_CONFIG: /config/ts-config.json
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    volumes:
      - ts-jellyfin-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
    