name: dozzle

volumes:
  ts-dozzle-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  dozzle:
    image: amir20/dozzle:v8.14.5
    network_mode: service:ts-dozzle
    depends_on:
      - ts-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ts-dozzle:
    image: tailscale/tailscale:stable
    hostname: dozzle
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container --reset
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
      TS_USERSPACE: false
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
