name: dozzle

volumes:
  ts-dozzle-state:

services:
  dozzle:
    image: amir20/dozzle:v7.0.7
    network_mode: service:ts-dozzle
    depends_on:
      - ts-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  ts-dozzle:
    image: tailscale/tailscale:v1.68.1
    hostname: dozzle
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY:?required TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container --reset
      TS_SERVE_CONFIG: /config/dozzle.json
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-dozzle-config
        target: /config/dozzle.json
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

configs:
  ts-dozzle-config:
    name: ts-dozzle-config
    file: ./ts-dozzle/config/dozzle.json