name: dozzle

volumes:
  ts-dozzle-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  dozzle:
    image: amir20/dozzle:v8.0.7
    network_mode: service:ts-dozzle
    depends_on:
      ts-dozzle:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  ts-dozzle:
    image: tailscale/tailscale:v1.68.1
    hostname: dozzle
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped
