name: uptime-kuma

volumes:
  uptime-kuma-data:
  ts-uptime-kuma-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13
    depends_on:
      ts-uptime-kuma:
        condition: service_healthy
    network_mode: service:ts-uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  ts-uptime-kuma:
    image: tailscale/tailscale:v1.72.1
    hostname: uptime-kuma
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    volumes:
      - ts-uptime-kuma-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped