name: uptime-kuma

volumes:
  uptime-kuma-data:
  ts-uptime-kuma-state:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13
    network_mode: service:ts-uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  ts-uptime-kuma:
    image: tailscale/tailscale:v1.66.4
    hostname: uptime-kuma
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY:?required TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_SERVE_CONFIG: /config/uptime-kuma.json
      TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - ts-uptime-kuma-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-uptime-kuma-config
        target: /config/uptime-kuma.json
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

configs:
  ts-uptime-kuma-config:
    name: ts-uptime-kuma-config
    file: ./ts-uptime-kuma/config/uptime-kuma.json