name: uptime-kuma

volumes:
  uptime-kuma-data:
  ts-uptime-kuma-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    depends_on:
      ts-uptime-kuma:
        condition: service_started
    network_mode: service:ts-uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  ts-uptime-kuma:
    image: tailscale/tailscale:stable
    hostname: uptime-kuma
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
    environment:
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    devices:
       - /dev/net/tun:/dev/net/tun
    volumes:
      - ts-uptime-kuma-state:/var/lib/tailscale
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped