name: transmission

volumes:
  transmission-config:
  ts-transmission-state:

configs:
  ts-config:
    file: ./ts-config.json

services:
  transmission:
    image: linuxserver/transmission:4.0.6
    depends_on:
      ts-transmission:
        condition: service_healthy
    network_mode: service:ts-transmission
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      PUID: 1000
      PGID: 1000
      # Add docker mods:
      # - https://github.com/linuxserver/docker-mods/tree/transmission-floodui
      DOCKER_MODS: linuxserver/mods:transmission-floodui
    volumes:
      - transmission-config:/config
      - /data/downloads:/downloads
      - /data/torrent:/watch
    restart: unless-stopped
  
  ts-transmission:
    image: tailscale/tailscale:v1.70.0
    hostname: transmission
    healthcheck:
      test: ["CMD-SHELL", "tailscale", "-c", "1", "hello.ts.net"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 7s
    cap_add:
      - net_admin
      - sys_module
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Budapest
      # generate an OAuth client token
      # - select Devices: Write
      # - select an appropriate tag, for example: container
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/ts-config.json
    volumes:
      - ts-transmission-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    configs:
      - source: ts-config
        target: /config/ts-config.json
    restart: unless-stopped