use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 1
  autocomplete: "duckduckgo"

server:
  limiter: false
  image_proxy: true

redis:
  url: redis://localhost:6379/0

ui:
  static_use_hash: true
  center_alignment: true
  infinite_scroll: true
  results_on_new_tab: true

categories_as_tabs:
  general:
  images:
  videos: