name: Deploy Transmission

on:
    push:
        branches: [ "main" ]
        paths:
        - 'transmission/**'
    workflow_dispatch:

env:
    SERVICE_NAME: transmission
    SERVICE_DIR: transmission
    HOST: ${{ secrets.SOLITUDE_HOST }}
    REMOTE_DIR: ${{ secrets.SOLITUDE_DEPLOY_DIR }}

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - run: rsync -avz --del $SERVICE_DIR $HOST:$REMOTE_DIR/
            
            - name: Deploy
              env: 
                DEPLOY_DIR: $REMOTE_DIR/$SERVICE_NAME
                PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
                CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
                CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
                SECRET_PATH: /services/$SERVICE_NAME
              run: |
                ssh $HOST "
                    set -o pipefail
                    cd $DEPLOY_DIR
                    export INFISICAL_DISABLE_UPDATE_CHECK=true
                    export INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=$CLIENT_ID --client-secret=$CLIENT_SECRET --silent --plain)
                    infisical run --projectId=$PROJECT_ID --path=$SECRET_PATH --env=prod --command='docker compose up -d --pull always --force-recreate'
                "