name: Deploy Transmission

on:
    push:
        branches: [ "main" ]
        paths:
        - 'transmission/**'
    workflow_dispatch:

env:
    SERVICE_NAME: transmission
    SERVICE_DIR: transmission
    HOST: ${{ secrets.SOLITUDE_HOST }}
    REMOTE_DIR: ${{ secrets.SOLITUDE_DEPLOY_DIR }}

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - run: rsync -avz --del $SERVICE_DIR $HOST:$REMOTE_DIR/
            - run: rsync -avz service_deploy.sh $HOST:$REMOTE_DIR/$SERVICE_DIR
            - run: rsync -avz .infisical.json $HOST:$REMOTE_DIR/$SERVICE_DIR
            
            - name: Deploy
              env: 
                DEPLOY_DIR: ${{ secrets.SOLITUDE_DEPLOY_DIR }}/transmission
                PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
                CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
                CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
                SECRET_PATH: /services/transmission
              run: |
                ssh $HOST "
                    cd \"$DEPLOY_DIR\" || exit
                    export PROJECT_ID=$PROJECT_ID
                    export CLIENT_ID=$CLIENT_ID
                    export CLIENT_SECRET=$CLIENT_SECRET
                    export SECRET_PATH=$SECRET_PATH
                    ./service_deploy.sh
                "