name: Deploy Transmission

on:
    push:
        branches: [ "main" ]
        paths:
        - 'transmission/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Deploy
              run: |
                rsync -avz --del transmission ${{ secrets.SOLITUDE_HOST }}:${{ secrets.SOLITUDE_DEPLOY_DIR }}/
                ssh ${{ secrets.SOLITUDE_HOST }} "\
                    export INFISICAL_DISABLE_UPDATE_CHECK=true && \
                    export INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=${{ secrets.INFISICAL_CLIENT_ID }} --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }} --silent --plain) && \
                    cd ${{ secrets.SOLITUDE_DEPLOY_DIR }}/transmission && \
                    infisical run --projectId=${{ secrets.INFISICAL_PROJECT_ID }} --path=/services/transmission --env=prod --command=\"docker compose up -d --force-recreate\" \
                    "