name: Deploy Linkarr

on:
    push:
        branches: [ "main" ]
        paths:
        - 'linkarr/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Deploy
              uses: ./.github/actions/deploy-without-secrets
              with:
                host: ${{ secrets.SOLITUDE_HOST }}
                service_root_dir: ${{ secrets.SOLITUDE_DEPLOY_DIR }}
                service_dir_name: linkarr